CLIENT: "findlyats"

TIMEOUT: 15

#ADMIN: "at_admin"
#ADMIN_PASSWORD: "Findly1234"
ADMIN: "sanAdmin"
ADMIN_PASSWORD: "$findly123$"
RECRUITER: "at_recruiter"
RECRUITER_PASSWORD: "Findly123"
HM: "at_hiringmanager"
HM_PASSWORD: "Findly123"
FIRST_ADVANTAGE: "msumner"
FIRST_ADVANTAGE_PASSWORD: "msumner"


EXTERNAL_CANDIDATE_EMAIL: "sanjeev.gupta@test.com"
EXTERNAL_CANDIDATE_PASSWORD: "111111"
INTERNAL_CANDIDATE_EMAIL: "internalauto@findly.com"
INTERNAL_CANDIDATE_PASSWORD: "bee123"

EXISTING_JOB_TEMPLATE: "Do Not Delete AT Job Template"
EXISTING_QUESTION_GROUP: ""
EXISTING_JOB: ""

EXISTING_ADMIN_USER: "sanAdmin"
EXISTING_ADMIN_PASSWORD: "$findly123$"
NEW_PASSWORD: "$123findly$"
